# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      #- develop
      #- feature/azure*

variables:
  buildConfiguration: "Release"
  artifactName: "testing-drop"
  artifactDirProject: "Project"
  buildPathRootProject: "MyAPI1"
  buildPathProject: "$(buildPathRootProject)/*.csproj"
  shouldRestoreProject: true
  buildVersion: ''

jobs:
  - job: TestAzurePipeline
    displayName: "Test Azure Pipeline"
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '6.x'

    

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - checkout: self
      clean: true

    - task: DotNetCoreCLI@2
      displayName: 'Install GitVersion'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global GitVersion.Tool --version 5.*'

    - task: PowerShell@2
      displayName: 'Set Build Version from GitVersion'
      inputs:
        targetType: inline
        script: |
          $version = dotnet-gitversion /showvariable SemVer
          echo $version
          echo "##vso[task.setvariable variable=buildVersion]$version"
    - task: DotNetCoreCLI@2
      displayName: 'Project | Restore'
      inputs:
        command: 'restore'
        projects: '$(buildPathProject)'
        feedsToUse: 'config'
        nugetConfigPath: 'NuGet.Config'

    - task: DotNetCoreCLI@2
      displayName: 'Project | Build'
      inputs:
        command: 'build'
        projects: '$(buildPathProject)'
        arguments: "--configuration $(buildConfiguration) -p:Version=$(buildVersion);FileVersion=$(buildVersion)"


    - task: DotNetCoreCLI@2
      displayName: 'Project | Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(buildPathProject)'
        arguments: '--no-build --no-restore --configuration $(buildConfiguration) --framework net6.0 --output $(build.artifactstagingdirectory)/$(artifactDirProject)'
        zipAfterPublish: true
    
    - task: DotNetCoreCLI@2
      displayName: 'Project | Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(buildPathProject)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Project | Nuget Push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'e632e806-6077-41a6-8789-41cc36178f28'

    - task: PublishBuildArtifacts@1
      displayName: 'Project | Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(artifactDIrProject)'
        ArtifactName: '$(artifactName)'
        publishLocation: Container
      enabled: true
